[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blob = "65HYZvHRH68nuqhrYmpqTLmdYy5Ex43PzT4fBAVp6EdF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/cenwadike/.config/solana/solfate-dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
