[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blob = "ApGdRJEbnNy4jWJWuWav6pwT84Tihdc5e5VfnAQujugr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/cenwadike/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
